@echo off
REM Enable collector mode for THIS PC only (auto-capture during farm).
REM Does not start the panel — sets a helper env file + prints commands.
setlocal EnableExtensions
cd /d "%~dp0"

set "ENVFILE=%~dp0data\capture_collector.env.bat"
if not exist "%~dp0data" mkdir "%~dp0data"

(
  echo @echo off
  echo REM Generated by EnableAutoCapture.bat — collector PC only
  echo set CSGOBOT_AUTO_CAPTURE=1
  echo set CSGOBOT_CAPTURE_INTERVAL_SEC=1.2
  echo set CSGOBOT_CAPTURE_MAX_PER_HOUR=400
  echo set CSGOBOT_CAPTURE_MAX_MB=2048
  echo set CSGOBOT_CAPTURE_SOFT_CT=1
  echo set CSGOBOT_CAPTURE_WHEN_TEAM_T_BOOST=1
  echo set CSGOBOT_CAPTURE_SOFT_LABELS=1
  echo set CSGOBOT_CAPTURE_EMPTY_SCENE=1
  echo set CSGOBOT_CAPTURE_EMPTY_INTERVAL_SEC=2.5
  echo set CSGOBOT_DETECT_DEBUG=1
  echo REM Prefer softer CT detect while collecting:
  echo set CSGOBOT_CONF_C=0.38
  echo set CSGOBOT_CONF_CH=0.40
  echo set CSGOBOT_CONF_T=0.50
  echo set CSGOBOT_CONF_TH=0.52
) > "%ENVFILE%"

echo.
echo === Collector mode env written ===
echo   %ENVFILE%
echo.
echo Before FarmPanel / csgobot on THIS PC:
echo   call data\capture_collector.env.bat
echo   FarmPanel.bat
echo.
echo Captures land in:
echo   vendor\csgobot\data\captures\
echo.
echo After sessions: BuildOurCs2FromRaw.bat  then train.
echo For texture FP: EnableHardNegCapture.bat + BuildHardNegativesFromRaw.bat
echo Docs: docs\AUTO_CAPTURE.md  docs\HARD_NEGATIVES.md
echo.
exit /b 0
