@echo off
REM Collector mode: HARD NEGATIVES only (map textures with EMPTY labels).
REM Walk Mirage/Dust2 looking at crates/walls/cars — YOLO may false-fire; we save empty.
REM Do NOT mix with CT soft-label collector in the same session.
setlocal EnableExtensions
cd /d "%~dp0"

set "ENVFILE=%~dp0data\capture_hardneg.env.bat"
if not exist "%~dp0data" mkdir "%~dp0data"

(
  echo @echo off
  echo REM Generated by EnableHardNegCapture.bat — texture FP collector
  echo set CSGOBOT_AUTO_CAPTURE=1
  echo set CSGOBOT_CAPTURE_HARD_NEG=1
  echo set CSGOBOT_CAPTURE_HARD_NEG_INTERVAL_SEC=1.0
  echo set CSGOBOT_CAPTURE_EMPTY_SCENE=1
  echo set CSGOBOT_CAPTURE_INTERVAL_SEC=1.0
  echo set CSGOBOT_CAPTURE_MIN_INTERVAL_SEC=0.6
  echo set CSGOBOT_CAPTURE_MAX_PER_HOUR=500
  echo set CSGOBOT_CAPTURE_MAX_MB=2048
  echo set CSGOBOT_CAPTURE_SOFT_LABELS=1
  echo set CSGOBOT_DETECT_DEBUG=1
  echo REM Keep combat conf so FPs still appear in detections for texture_fp trigger:
  echo set CSGOBOT_CONFIDENCE=0.45
) > "%ENVFILE%"

echo.
echo === Hard-negative collector env written ===
echo   %ENVFILE%
echo.
echo Usage:
echo   call data\capture_hardneg.env.bat
echo   FarmPanel.bat   ^(or vendor\csgobot run.py^)
echo.
echo Walk empty map areas ^(crates, walls, cars^). Caps Lock ON.
echo Captures force EMPTY labels even if YOLO boxes textures.
echo.
echo After sessions:
echo   BuildHardNegativesFromRaw.bat
echo   then merge hard_negatives into product + TrainProductModel.bat
echo.
echo Docs: docs\HARD_NEGATIVES.md
echo.
exit /b 0
