@echo off
REM Runtime band-aid: raise detect conf to cut texture FP until new weights.
setlocal EnableExtensions
cd /d "%~dp0"

set "ENVFILE=%~dp0data\fp_guard.env.bat"
if not exist "%~dp0data" mkdir "%~dp0data"

(
  echo @echo off
  echo REM Generated by EnableFpGuard.bat — temporary FP reduction
  echo set CSGOBOT_CONFIDENCE=0.58
  echo set CSGOBOT_CONF_C=0.58
  echo set CSGOBOT_CONF_CH=0.60
  echo set CSGOBOT_CONF_T=0.55
  echo set CSGOBOT_CONF_TH=0.55
  echo set CSGOBOT_DETECT_DEBUG=1
) > "%ENVFILE%"

echo.
echo === FP guard env written ===
echo   %ENVFILE%
echo.
echo Before farm:
echo   call data\fp_guard.env.bat
echo   FarmPanel.bat
echo.
echo If real CT/T vanish in close fights, lower to 0.52-0.55.
echo Real fix: hard negatives + retrain ^(EnableHardNegCapture.bat^).
echo.
exit /b 0
